# Site settings
title: Optimising for fun
header-img: img/home-bg-2.jpg
email: will.ockmore@gmail.com
copyright_name: William Ockmore
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username:
github_username:  will-ockmore
facebook_username:
email_username:  will.ockmore@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
